const constants = {
  BTC_ASK_ADDED: "BTC_ASK_ADDED",
  BTC_ASK_DESTROYED: "BTC_ASK_DESTROYED",
  BTC_BID_ADDED: "BTC_BID_ADDED",
  BTC_BID_DESTROYED: "BTC_BID_DESTROYED",

  BCH_ASK_ADDED: "BCH_ASK_ADDED",
  BCH_ASK_DESTROYED: "BCH_ASK_DESTROYED",
  BCH_BID_ADDED: "BCH_BID_ADDED",
  BCH_BID_DESTROYED: "BCH_BID_DESTROYED",

  PYY_ASK_ADDED: "PYY_ASK_ADDED",
  PYY_ASK_DESTROYED: "PYY_ASK_DESTROYED",
  PYY_BID_ADDED: "PYY_BID_ADDED",
  PYY_BID_DESTROYED: "PYY_BID_DESTROYED",

  GDS_ASK_ADDED: "GDS_ASK_ADDED",
  GDS_ASK_DESTROYED: "GDS_ASK_DESTROYED",
  GDS_BID_ADDED: "GDS_BID_ADDED",
  GDS_BID_DESTROYED: "GDS_BID_DESTROYED"
}

module.exports = constants;
